# API Aegir

## Group Applications

### /apps

#### Récupérer la liste des applications [GET]

+ Parameters
  + running (boolean, optional) Ne récupérer que les applications en cours d'exécution

#### Démarrer une nouvelle application [POST]

+ Request (application/json)
  + Body
    {
      
    }
